### ISSUE TITLE
Challenge 4 Error

### ISSUE THREAD

**Issue by ValerieLynn25** [CourseReps/ECEN303-Summer2015#8]
We get 2s in our received message with the professor's code. Anyone else getting this? And if so, are you all assuming that just means a 0 was received when a 1 was sent?

**Comment by chmbrlnd** [comment]
Hello,

There was an issue with the Python code I provided for Challenge 4. I realized the problem while grading the challenge. The code has been updated on GitHub. You are not required to fix your own code, as you should now focus on Challenge 5. Grades will take this issue into consideration.

def channel(inputsymbol):
    channelnoise = math.floor(random.random() + 0.2)
    return math.floor((inputsymbol + channelnoise) % 2.0)

Best regards,
Jean-Francois Chamberland
